name: Auto Generate Rules

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 10 */3 * *'

jobs:
  build:
    name: Check and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Apple Rule
        run: |
          python ruleset.py \
            --source https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Apple.list        \
            > Apple.list

      - name: Generate China Rule
        run: |
          python ruleset.py \
            --source https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Domestic.list \
            --exclude DOMAIN-SUFFIX,cn \
            --exclude DOMAIN-SUFFIX,ip.sb \
            > China.list

      - name: Generate Global Rule
        run: |
          python ruleset.py \
            --source https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Proxy.list \
            --source DOMAIN-SUFFIX,cdn.jsdelivr.net \
            > Global.list

      - name: Generate Media Rule
        run: |
          python ruleset.py \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Netflix/Netflix.list                   \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Disney/Disney.list                     \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/TikTok/TikTok.list                     \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AmazonPrimeVideo/AmazonPrimeVideo.list \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list                   \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTubeMusic/YouTubeMusic.list         \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/HBO/HBO.list                           \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Hulu/Hulu.list                         \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitch/Twitch.list                     \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Spotify/Spotify.list                   \
            > Media.list

      - name: Generate MediaCN Rule
        run: |
          python ruleset.py \
            --source https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/Bilibili.list               \
            --source https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Media/IQIYI.list                  \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/NetEaseMusic/NetEaseMusic.list \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/TencentVideo/TencentVideo.list \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Youku/Youku.list               \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Sohu/Sohu.list                 \
            > MediaCN.list

      - name: Generate Microsoft Rule
        run: |
          python ruleset.py \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list  \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Teams/Teams.list          \
            > Microsoft.list

      - name: Generate PayPal Rule
        run: |
          python ruleset.py \
            --source https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PayPal/PayPal.list \
            > PayPal.list

      - name: Generate Reject Rule
        run: |
          python ruleset.py --force-no-resolve \
            --source https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Reject.list \
            > Reject.list

      - name: Generate Steam Rule
        run: |
          python ruleset.py \
            --source https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Steam.list \
            > Steam.list

      - name: Generate Telegram Rule
        run: |
          python ruleset.py \
            --source https://raw.githubusercontent.com/dler-io/Rules/master/Surge/Surge%203/Provider/Telegram.list           \
            > Telegram.list

      - name: Convert Clash Rules
        run: |
          for rule in *.list
          do
            python ruleset.py -c -s "file://$PWD/$rule" > "${rule%.*}.yaml"
          done

      - name: Push to Branch
        run: |
          git config --global user.name  'xjasonlyu'
          git config --global user.email 'xjasonlyu@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}

          git checkout release

          mkdir -p Clash && cp -rf *.yaml Clash/
          mkdir -p Surge && cp -rf *.list Surge/

          git add Clash/*
          git add Surge/*

          git commit -m "Update $(date -u +%Y%m%d%H%M%S)" && git push origin release || echo "nothing to commit"
